sibers_blog:
    resource: "@SibersBlogBundle/Controller/"
    type:     annotation


SibersBlogBundle_mainpage:
    path:     /
    defaults: { _controller: "SibersBlogBundle:mainPage:index" }
    requirements:
         methods:  GET



SibersBlogBundle_about:
    path:   /about
    defaults: { _controller: "SibersBlogBundle:About:about" }
    requirements:
         methods:  GET


SibersBlogBundle_contact:
    path:  /contact
    defaults: { _controller: "SibersBlogBundle:Contact:contact" }
    requirements:
        methods:  GET|POST



SibersBlogBundle_blog_show:
    path:  /{id}/{slug}
    defaults: { _controller: "SibersBlogBundle:Blog:show" }
    requirements:
        methods:  GET
        id: \d+


SibersBlogBundle_comment_create:
    path:  /comments{blog_id}
    defaults: { _controller: "SibersBlogBundle:Comment:create" }
    requirements:
        methods:  POST
        id: \d+
