sibers_blog:
    resource: "@SibersBlogBundle/Controller/"
    type:     annotation


SibersBlogBundle_mainpage:
    path:     /
    defaults: { _controller: "SibersBlogBundle:mainPage:index" }
    requirements:
         methods:  GET
